version: '3.6'

services:

################################################
#####       Setup MySQL containers        ######
################################################
  person_db:
    container_name: person_api_db
    image: "postgres:${SERVER_ENGINE_VERSION}"
    ports:
      - "${LOCAL_DB_PORT}:${SERVICE_PORT}"
    expose:
      - "${SERVICE_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

################################################
#####       Volumes Configuration         ######
################################################

volumes:
  person_db:
    driver: local
